### ISSUE TITLE
AttributeError: 'module' object has no attribute '_base'

### ISSUE THREAD

**Issue by hasanzuav** [kirkthaker/investopedia-trading-api#12]
I wrote the following script:

```
from investopedia import *
client = Account("emailaddress","password") #replaced with my info

status = client.get_portfolio_status()
print status.account_val
print status.buying_power
print status.cash
print status.annual_return
```
I was able to install all the modules by running py -2.7 setup.py install for each dependency.

I am receiving the following error:

```
Traceback (most recent call last):
File "C:/Users/Z/PycharmProjects/investopedia/test.py", line 1, in <module>
    from investopedia import *
  File "C:\Users\Z\PycharmProjects\investopedia\investopedia.py", line 4, in <module>
    from bs4 import BeautifulSoup
  File "C:\Users\Z\AppData\Local\Enthought\Canopy\User\lib\site-packages\bs4\__init__.py", line 29, in <module>
    from .builder import builder_registry
  File "C:\Users\Z\AppData\Local\Enthought\Canopy\User\lib\site-packages\bs4\builder\__init__.py", line 297, in <module>
    from . import _html5lib
  File "C:\Users\Z\AppData\Local\Enthought\Canopy\User\lib\site-packages\bs4\builder\_html5lib.py", line 57, in <module>
    class TreeBuilderForHtml5lib(html5lib.treebuilders._base.TreeBuilder):
AttributeError: 'module' object has no attribute '_base'
```
Do you know how to resolve this?

**Comment by hasanzuav** [comment]
Solved this by using 
```
pip2.7 install --upgrade beautifulsoup4
pip2.7 install --upgrade html5lib
```

Works beautifully now.
