### ISSUE TITLE
get_portfolio_status() returns AttributeError

### ISSUE THREAD

**Issue by MSXR** [kirkthaker/investopedia-trading-api#23]
3 lines:

from InvestopediaApi import ita
inv = ita.Account("email", "pwd")
inv.get_portfolio_status()

returns

Traceback (most recent call last):
  File "/Users/Ember/Documents/BitBot/main.py", line 3, in <module>
    inv.get_portfolio_status()
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/InvestopediaApi/ita.py", line 67, in get_portfolio_status
    account_value = parsed_html.find('span', attrs={'id': acct_val_id}).text
AttributeError: 'NoneType' object has no attribute 'text'

any ideas? thanks.

**Comment by MSXR** [comment]
Ah Sorry Just realise this is already fixed

**Comment by kirkthaker** [comment]
Please add a link to the solution in case anyone else stumbles on this issue, thanks!

**Comment by MSXR** [comment]
link, #5
