### ISSUE TITLE
Failed to handle prices more than 1000

### ISSUE THREAD

**Issue by tycheng** [kirkthaker/investopedia-trading-api#24]
ita.get_quote("GOOG")

The code simply uses float() to do type cast, without handling the corner cases where values
greater than 3 digits uses comma as separator.

Traceback (most recent call last):
  File "./launcher.py", line 53, in <module>
    main(parse_args())
  File "./launcher.py", line 48, in main
    app.run()
  File "/home/tcheng/Repositories/spice/spice/watcher.py", line 31, in run
    self._check_stock_prices_()
  File "/home/tcheng/Repositories/spice/spice/watcher.py", line 56, in _check_stock_prices_
    print(ita.get_quote("GOOG"))
  File "/home/tcheng/Repositories/spice/venv/lib/python3.6/site-packages/InvestopediaApi/ita.py", line 261, in get_quote
    return float(quote)
ValueError: could not convert string to float: '1,029.27'

**Comment by josiahdahl** [comment]
There's a PR open for this - https://github.com/kirkthaker/investopedia-trading-api/pull/20. Hopefully it'll get merged soon.
