### ISSUE TITLE
Error when trying to log in. 

### ISSUE THREAD

**Issue by Bulmenisaurus** [kirkthaker/investopedia-trading-api#27]
I was trying to use this api, but encountered problems upon logging in. Here is the full error:
```python
Traceback (most recent call last):
  File "/Users/meow/programming/PycharmProjects/testing/Investopedia trading.py", line 7, in <module>
    client = ita.Account(account_info[0], account_info[1])
  File "/Users/meow/Maths100%/venv/lib/python3.8/site-packages/InvestopediaApi/ita.py", line 40, in __init__
    login_form = login_page.soup.select("form#account-api-form")[0]
IndexError: list index out of range
```
`account_info[0]` and `account_info[1]` is the login information. Seeing how old the commits are, I'll probably look for a more active API.

**Comment by glotchimo** [comment]
My guess is that the ID has changed for whatever that element is on the Investopedia site so BeautifulSoup isn't able to grab it since it's hard-coded with a potentially stale value. I'd investigate that first if I were you, could be a quick and easy PR

**Comment by Bulmenisaurus** [comment]
Ok, I think i fixed the problem, but I don't have the slightest clue on how to test the module locally. :(

**Comment by VenomStyx** [comment]
Also experiencing this issue :/

**Comment by MrQui2** [comment]
I have the same issue as Bulmenisaurus. Nothing worked. How can I fix it. I have Python 3.9

**Comment by SoggyWaffle27** [comment]
Has anyone solved this yet?

**Comment by Bulmenisaurus** [comment]
@SoggyWaffle27 try applying the changes in https://github.com/kirkthaker/investopedia-trading-api/pull/28.
